apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis8a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session8a
      tier: redis8a
  template:
    metadata:
      labels:
        app: session8a
        tier: redis8a
    spec:
      containers:
      - name: redis8a
        image: "redis:alpine"
        ports:
        - containerPort: 6379
