apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session8
      tier: redis
  template:
    metadata:
      labels:
        app: session8
        tier: redis
    spec:
      containers:
      - name: redis
        image: "redis:alpine"
        ports:
        - containerPort: 6379
