apiVersion: v1
kind: Service
metadata:
  name: redis8a
  labels:
    app: session8a
    tier: redis8a
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: session8a
    tier: redis8a