apiVersion: v1
kind: Pod
metadata:
  name: probe-app
  labels:
    app: probe-app
spec:
  containers:
    - name: dotnet-probe-app
      image: kevinciq/session11
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /WeatherForecast/liveness
          port: 80
        initialDelaySeconds: 80
        periodSeconds: 30
      readinessProbe:
        httpGet:
          path: /WeatherForecast/readiness
          port: 80
        initialDelaySeconds: 30
        timeoutSeconds: 30
        periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: probe-app-service
spec:
  selector:
    app: probe-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer