apiVersion: v1
kind: Pod
metadata:
  name: probe-app
  labels:
    app: probe-app
spec:
  containers:
    - name: dotnet-probe-app
      image: session11
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: $(slug)/api/home/info
          port: $((containerPort))
        initialDelaySeconds: 60
        periodSeconds: 30
      readinessProbe:
        httpGet:
          path: $(slug)/api/home/info
          port: $((containerPort))
        initialDelaySeconds: 30
        timeoutSeconds: 30
        periodSeconds: 30       
---
apiVersion: v1
kind: Service
metadata:
  name: sidecar-service
spec:
  selector:
    app: probe-app
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer