apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask8a
spec:
  replicas: 3
  selector:
    matchLabels:
        app: session8a
        tier: flask8a
  template:
    metadata:
      labels:
        app: session8a
        tier: flask8a
    spec:
      containers:
      - name: flaskapp8a
        image: kevinciq/session8a:flask
        ports:
        - containerPort: 5000