apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 3
  selector:
    matchLabels:
        app: session8
        tier: flask
  template:
    metadata:
      labels:
        app: session8
        tier: flask
    spec:
      containers:
      - name: flaskapp
        image: kevinciq/session8:flask
        ports:
        - containerPort: 5000