apiVersion: v1
kind: Pod
metadata:
  name: sidecar
  labels:
    app: web-server
spec:
  containers:
    - name: apache-web-server
      image: httpd
      ports:
        - containerPort: 80
    - name: nginx-ssl-terminator
      image: nginx
      ports:
        - containerPort: 443
      volumeMounts:
        - name: cert
          mountPath: /etc/certstore/
        - name: key
          mountPath: /etc/keystore/
        - name: config
          mountPath: /etc/nginx/conf.d/
  volumes:
    - name: cert
      secret:
        secretName: s10cert
    - name: key
      secret:
        secretName: s10key
    - name: config
      configMap:
        name: nginx-ssl-terminator
---
apiVersion: v1
kind: Service
metadata:
  name: sidecar-service
spec:
  selector:
    app: web-server
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer